lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: '%env(JWT_TTL)%'
  user_identity_field: email
  token_extractors:
    authorization_header:
      enabled: false
    cookie:
      enabled: true
      name: '%env(AUTH_COOKIES_PREFIX)%''%env(JWT_COOKIE_NAME)%'
